[phases.setup]
nixPkgs = ["{ maven, openjdk17 }"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[phases.build]
cmds = ["true"]

[start]
cmd = "java -jar target/backend-altave-0.0.1-SNAPSHOT.jar"

[variables]
PORT = "8080"

